# Generated by Django 6.0.2 on 2026-04-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_vaultitem_item_file_alter_vaultitem_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vault',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaultitem',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
