# Generated by Django 6.0.2 on 2026-03-15 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultitem',
            name='item_file',
            field=models.FileField(blank=True, null=True, upload_to='vault_files/'),
        ),
        migrations.AlterField(
            model_name='vaultitem',
            name='item_type',
            field=models.CharField(choices=[('LOG', 'Login'), ('NOT', 'Note'), ('DOC', 'Document')], default='LOG', max_length=3),
        ),
    ]
